# Generated by Django 3.0.2 on 2020-09-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('ephone_number', models.BigIntegerField()),
                ('esalary', models.IntegerField()),
                ('eaddress', models.CharField(max_length=50)),
            ],
        ),
    ]
